# Generated by Django 5.2.8 on 2025-11-20 15:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_image_product_stock_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
